In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv('diabetes_data.csv')

In [3]:
# slicing features and target arrays
#X = data.iloc[:,[0,1,2,3,4,5,6,7]].values
X= data.iloc[0:767].values
Y= data.iloc[0:767,[8]].values
#Y= data.iloc[:,-1].values
print(X)
print(Y)

[[1.00e+00 8.50e+01 6.60e+01 ... 3.51e-01 3.10e+01 0.00e+00]
 [8.00e+00 1.83e+02 6.40e+01 ... 6.72e-01 3.20e+01 1.00e+00]
 [1.00e+00 8.90e+01 6.60e+01 ... 1.67e-01 2.10e+01 0.00e+00]
 ...
 [5.00e+00 1.21e+02 7.20e+01 ... 2.45e-01 3.00e+01 0.00e+00]
 [1.00e+00 1.26e+02 6.00e+01 ... 3.49e-01 4.70e+01 1.00e+00]
 [1.00e+00 9.30e+01 7.00e+01 ... 3.15e-01 2.30e+01 0.00e+00]]
[[0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0

In [4]:
#target flattening and replacing zero with minus one

Y = np.ndarray.flatten(Y)
Y[Y==0]=-1
print(Y) # picks y array and replace it with minus one

[-1  1 -1  1 -1  1 -1  1  1 -1  1 -1  1  1  1  1  1 -1  1 -1 -1  1  1  1
  1  1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1  1  1 -1 -1 -1  1 -1  1 -1 -1  1
 -1 -1 -1 -1  1 -1 -1  1 -1 -1 -1 -1  1 -1 -1  1 -1  1 -1 -1 -1  1 -1  1
 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1 -1 -1 -1  1 -1 -1 -1 -1  1 -1 -1 -1
 -1 -1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1 -1 -1  1  1  1 -1 -1 -1  1
 -1 -1 -1  1  1 -1 -1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1
 -1 -1 -1 -1 -1 -1 -1  1 -1  1  1 -1 -1 -1  1 -1 -1 -1 -1  1  1 -1 -1 -1
 -1  1  1 -1 -1 -1  1 -1  1 -1  1 -1 -1 -1 -1 -1  1  1  1  1  1 -1 -1  1
  1 -1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1  1  1 -1  1 -1 -1 -1  1  1  1  1
 -1  1  1  1  1 -1 -1 -1 -1 -1  1 -1 -1  1  1 -1 -1 -1  1  1  1  1 -1 -1
 -1  1  1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1  1 -1  1 -1 -1  1
 -1  1 -1 -1  1  1 -1 -1 -1 -1 -1  1 -1 -1 -1  1 -1 -1  1  1 -1 -1  1 -1
 -1 -1  1  1  1 -1 -1  1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1  1 -1 -1  1
 -1  1 -1 -1  1 -1  1 -1  1  1  1 -1 -1  1 -1  1 -1

In [5]:
#spliting data into 80 percent training and 20 percent testing sets
X_train,X_test,Y_train,Y_test= train_test_split(X,Y,test_size=0.2,random_state=45)

In [7]:
#now train svm model and predict 

clf = svm.SVC()#kernel='poly',degree=5) #poly,degree = 2,rbf
clf.fit(X_train,Y_train)
pred_train = clf.predict(X_train)
pred_test = clf.predict(X_test)

In [8]:
acc1 = accuracy_score(Y_train,pred_train)
acc2 = accuracy_score(Y_test,pred_test)

print("Training accuracy =",acc1)
print("Testing accuracy =",acc2)

Training accuracy = 0.766721044045677
Testing accuracy = 0.7597402597402597
